apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-tekton-operators-proxy-webhook
rules:
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - scc-tekton-operators-proxy-webhook 
  resources:  
   - securitycontextconstraints  # <-- ??? 
  verbs: 
  - use